export const ERROR = 'ERROR';
export const CHANGE_LOADING = 'CHANGE_LOADING';

export const GET_CLIENTS = 'GET_CLIENTS';
export const GET_CLIENT_BY_ID = 'GET_CLIENT_BY_ID';
export const ADD_CLIENT = 'ADD_CLIENT';
export const UPDATE_CLIENT = 'UPDATE_CLIENT';
export const DELETE_CLIENT = 'DELETE_CLIENT';


export const GET_PROVIDERS = 'GET_PROVIDERS';
export const ADD_PROVIDER = 'ADD_PROVIDER';
export const DELETE_PROVIDER = 'DELETE_PROVIDER';
export const UPDATE_PROVIDER = 'UPDATE_PROVIDER';
